@startuml

skinparam Linetype ortho
skinparam Nodesep 60
skinparam Ranksep 60

class Engine {
    + void run(width, height, );
}
class GLFWindow {}
GLFWindow <-- Engine

class Renderer {
    + void drawScene();
}
Renderer <-- Engine

class Shader {}
Shader <-- Renderer


'Here is where the magic happens, the animator should transform the entities attr.'
'Each entity has a position, scale and rotation'
'This class should be able to receive the path of some animations scripts.'
'this scripts are just text files that contain key words for animating'

'Scene is a class that contains all the entities within it'
class Scene {
    + bool loadScene(String path)
    + vector<Entity> getAllEntities();
}
Scene <-- Engine


package entities {
    interface entity {}
    class line {}
    class quad {}
    class curve {}
    class text {}
}
entities <-- Scene

class Animator {}
Animator<--Engine

package scenes {
    class intro_scene{}
    class explain_3dfunction{}
    class camera_angle_change{}
}

class Parser {}
Parser --> scenes
Parser <-- Scene
Parser <-- Animator


@enduml